name: Build, Checkstyle, Tests, Docker Image, and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build project
        run: mvn clean install

      - name: Notify success
        run: |
          echo "Build successful!"
          echo "Additional information or details about the build"

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Notify success
        run: |
          echo "Checkstyle successful!"
          echo "Additional information or details about the build"

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Run Tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest

  package:
    needs: [docker]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GitHub Packages
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/package:${{ github.run_id }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/package:${{ github.run_id }}
