name: Java-build
on:
  push:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run tests
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run test with Maven
        run: mvn -P github --settings ./.github/workflows/maven-settings.xml -B test
        env:
          USER_NAME: ${{ github.actor }}
          ACCESS_TOKEN: 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

  checkstyle_job:
    runs-on: ubuntu-latest
    needs: [test_job]
    name: Checkstyle job
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Checkstyle with Maven
        run: mvn checkstyle:check
  build:
    runs-on: ubuntu-latest
    needs: [checkstyle_job]
    name: Build service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B install -Dmaven.test.skip=true -Dcheckstyle.skip --file pom.xml
