name: Run_Checkstyle

on:
  push:
    branches:
      - actions

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Notify success
      run: |
          echo "Checkstyle successful!"
          echo "Additional information or details about the build"
